git-debimport libtext-charwidth-perl_0.04-7.debian.tar.bz2

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -18,13 +18,26 @@ ifeq (,$(findstring nostrip,$(DEB_BUILD_OPTIONS)))
 	INSTALL_PROGRAM += -s
 endif
 
+DEB_BUILD_GNU_TYPE      := $(shell dpkg-architecture -qDEB_BUILD_GNU_TYPE)
+DEB_HOST_GNU_TYPE       := $(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
+
+ifneq ($(DEB_HOST_GNU_TYPE),$(DEB_BUILD_GNU_TYPE))
+        HOST_PERL = $(shell which perl)
+        PERL_VER = $(shell $(HOST_PERL) -v | $(HOST_PERL) -e 'while(<>) {/v(\d+\.\d+\.\d+)/ and print "$$1\n";}')
+
+        export PERL5LIB=/usr/$(DEB_HOST_GNU_TYPE)/lib/perl/$(PERL_VER)
+endif
+
+
 configure: configure-stamp
 configure-stamp:
 	dh_testdir
 	touch configure-stamp
 
+build: build-arch build-indep
+build-arch: build-stamp
+build-indep: build-stamp
 build: build-stamp
-
 build-stamp: configure-stamp 
 	dh_testdir
 	perl Makefile.PL INSTALLDIRS=vendor
@@ -39,11 +52,19 @@ clean:
 	dh_clean Makefile.old Makefile CharWidth.o blib/arch/auto/Text/CharWidth/CharWidth.so blib/man3/Text::CharWidth.3pm CharWidth.c
 
 install: build
+ifneq ($(DEB_HOST_GNU_TYPE),$(DEB_BUILD_GNU_TYPE))
+	@if [ ! -f $(PERL5LIB)/Config.pm ] || [ ! -f $(PERL5LIB)/Config_heavy.pl ]	;\
+	then	\
+		echo "Config.pm & Config_heavy.pl for cross building not found in $(PERL5LIB)"	;\
+	exit 1	;\
+	fi
+endif
+	dh $@
 	dh_testdir
 	dh_testroot
 	dh_prep
 	dh_installdirs
-	$(MAKE) install PREFIX=`pwd`/debian/libtext-charwidth-perl/usr
+	$(MAKE) install DESTDIR=`pwd`/debian/libtext-charwidth-perl
 
 # Build architecture-independent files here.
 binary-indep: build install
